### ISSUE TITLE
setting up config

### ISSUE THREAD

**Issue by ElianoMarques** [rstudio/sparklyr#87]
Hi, 

I'm trying to change the config of the spark environment, similar to the way we do with SparkR package. 
```r
library(SparkR)
spark_env = list('spark.executor.memory' = '4g', 
                 'spark.executor.instances' = '4', 
                 'spark.executor.cores' = '4',
                 'spark.driver.memory' = '4g') 

sc <- sparkR.init(master = local[*], appName = "SparkR", sparkEnvir = spark_env, 
                  sparkJars=c("/home/sparkjars/spark-csv_2.10-1.3.0.jar", 
                              "/home/sparkjars/commons-csv-1.2.jar"))
```

In this package I did the following:

Inside the package folder there is a folder called config/config-template.yml and I changed that to:

```
default:
  # local-only configuration
  sparklyr.cores.local: !expr parallel::detectCores()
  sparklyr.shell.driver-memory: 4GB
  sparklyr.shell.executor-memory: 4GB
  sparklyr.sql.shuffle.partitions.local: !expr parallel::detectCores()
```

then I run:

```r
sc = spark_connect(master= "local[*]" )
#also tried sc = spark_connect(master= "local[*]" , config = list('sparklyr.shell.executor-memory'='4GB'))
```

I get the following error: 

```r
Error in instances[[scon$sconRef]] <- NULL : 
  attempt to select less than one element in OneIndex
```

Would be great if you could clarify how to define the config directly in r-studio and also comment on the error. 

Thank you
